//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BucketGame {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Props : global::System.Configuration.ApplicationSettingsBase {
        
        private static Props defaultInstance = ((Props)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Props())));
        
        public static Props Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("hh\\:mm\\:ss\\.fff")]
        public string TimeFormat {
            get {
                return ((string)(this["TimeFormat"]));
            }
            set {
                this["TimeFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("נראה כי אין פה אף אחד")]
        public string MessageCantSeePlayer {
            get {
                return ((string)(this["MessageCantSeePlayer"]));
            }
            set {
                this["MessageCantSeePlayer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("משחק")]
        public string TabHeaderStatus {
            get {
                return ((string)(this["TabHeaderStatus"]));
            }
            set {
                this["TabHeaderStatus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("טווח תנועה לא אותחל. יש לאתחל טווח תנועה לפני תחילת המשחק")]
        public string MessageMeasurementNotInitialize {
            get {
                return ((string)(this["MessageMeasurementNotInitialize"]));
            }
            set {
                this["MessageMeasurementNotInitialize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("בחירת מפרקים")]
        public string TabHeaderJointSelection {
            get {
                return ((string)(this["TabHeaderJointSelection"]));
            }
            set {
                this["TabHeaderJointSelection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>טוען את המשחק</string>
  <string>מכין את המשחק הנפלא ביותר בכל הזמנים</string>
  <string>מחפש תירוצים לזמן טעינת המשחק</string>
  <string>מחפש את התשובה לחיים, ליקום וכל השאר</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Excuses {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Excuses"]));
            }
            set {
                this["Excuses"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:03.5000000")]
        public global::System.TimeSpan TimeForExcuse {
            get {
                return ((global::System.TimeSpan)(this["TimeForExcuse"]));
            }
            set {
                this["TimeForExcuse"] = value;
            }
        }
    }
}
