//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BucketGame {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Props : global::System.Configuration.ApplicationSettingsBase {
        
        private static Props defaultInstance = ((Props)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Props())));
        
        public static Props Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("hh:mm:ss.fff")]
        public string TimeFormat {
            get {
                return ((string)(this["TimeFormat"]));
            }
            set {
                this["TimeFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("נראה כי אין פה אף אחד")]
        public string MessageCantSeePlayer {
            get {
                return ((string)(this["MessageCantSeePlayer"]));
            }
            set {
                this["MessageCantSeePlayer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("משחק")]
        public string TabHeaderStatus {
            get {
                return ((string)(this["TabHeaderStatus"]));
            }
            set {
                this["TabHeaderStatus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("טווח תנועה לא אותחל. יש לאתחל טווח תנועה לפני תחילת המשחק")]
        public string MessageMeasurementNotInitialize {
            get {
                return ((string)(this["MessageMeasurementNotInitialize"]));
            }
            set {
                this["MessageMeasurementNotInitialize"] = value;
            }
        }
    }
}
